name: Synthetic CSV Data

on:
  workflow_dispatch:
    inputs:
      csv_filename:
        description: 'CSV input filename (in inputs/ folder)'
        required: true
        default: 'input.csv'

      config_filename:
        description: 'Config YAML filename (in inputs/ folder)'
        required: true
        default: 'config.yaml'

      api_key:
        description: 'Select API provider'
        required: false
        default: 'groq'
        type: choice
        options:
          - groq
          - huggingface

      model:
        description: 'Select model name'
        required: false
        default: 'mistral-saba-24b'
        type: choice
        options:
          - llama3-70b-8192
          - llama3-8b-8192
          - mistral-saba-24b
          - gemma-9b-it
          - deepseek-r1-distill-llama-70b

      custom_param:
        description: 'Optional parameter (like mode/date)'
        required: false
        default: 'manual_run'

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pyyaml

      - name: Run Python Script with Inputs
        run: |
          echo "Running with model: ${{ github.event.inputs.model }} and provider: ${{ github.event.inputs.api_key }}"
          python script.py \
            "inputs/${{ github.event.inputs.csv_filename }}" \
            "inputs/${{ github.event.inputs.config_filename }}" \
            "${{ github.event.inputs.custom_param }}" \
            "${{ github.event.inputs.api_key }}" \
            "${{ github.event.inputs.model }}"

      - name: Upload Output as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: processed-output
          path: output/
